# Generated by Django 5.0.6 on 2024-05-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_photo_car_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='tipo',
        ),
    ]
